### ISSUE TITLE
Bug Report - my channel 

### ISSUE THREAD

**Issue by inchanS** [DawonOh/review-board#18]
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/8689777/235281375-f1548ec8-5209-440c-9a04-e2055c70f640.png">

내 채널 보기를 클릭하면 빈화면이 나옵니다. 
확인 부탁드려요

**Comment by DawonOh** [comment]
아직 만드는 중이라 main에 안올라가있어요. 빨리 만들어보겠습니다!

**Comment by DawonOh** [comment]
업데이트 완료했습니다. 이제 채널페이지 작동합니다.
