### ISSUE TITLE
비밀번호 재설정 링크 클릭시 연결페이지 오류?

### ISSUE THREAD

**Issue by inchanS** [DawonOh/review-board#26]
`비밀번호 찾기`를 통해 메일로 받은 `패스워드 재설정 링크` 클릭시
주소가 `localhost:3000`으로 설정되어있어요. 
확인 부탁드립니다. 
아래 이미지 첨부드려요 😭 

<img width="692" alt="image" src="https://github.com/DawonOh/review-board/assets/8689777/a1ec60fd-1075-4d4a-9904-64affcb9dc38">

**Comment by DawonOh** [comment]
해결했습니다! 다시 한번 해보시겠어요?

**Comment by inchanS** [comment]
잘됩니다!! 👍🏼
