### ISSUE TITLE
화면 너비 밸런스가 바뀐것 같아요

### ISSUE THREAD

**Issue by inchanS** [DawonOh/review-board#45]
주로 웹에서 보는데 뭔가 이전보다 **본문의 너비**가 줄어든것 같아요. 
본문 너비가 덧글 너비보다 더 줄어들었는데 바뀐건가요?? ; ㅋ

<img width="700" alt="SCR-20240320-ggtt" src="https://github.com/DawonOh/review-board/assets/8689777/662a0ca0-5b33-4a70-b26c-6c20344885b5">

모바일의 경우에는 전체적인 너비 한번 만지면 어떨까 싶어요. 

<img src="https://github.com/DawonOh/review-board/assets/8689777/0187300d-c82a-4a8a-b2dd-c0b014004b2d" width="500">

**Comment by DawonOh** [comment]
이미지 사이즈가 너무 커서 전체 사이즈를 줄였는데.. 조금 더 고민해보고 수정하겠습니다!
